name: Build Marshalsec

on:
  push:
    branches:
      - main # 或其他主分支
    paths:
      - '**/*' # 监测所有文件变更，也可以根据需要调整

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 需要写入权限来创建 release
    
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'mbechler/marshalsec'
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.392+8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven (Skip Tests)
      run: mvn -B clean package -DskipTests
        
    - name: List generated files
      run: ls -la target/
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.sha }}  # 使用当前 commit 的 SHA 作为版本标签
        name: Marshalsec Release ${{ github.sha }}  # 使用 commit SHA 作为发布名称
        draft: false
        prerelease: false
        files: |
          target/marshalsec-${{ github.sha }}-all.jar  # 将生成的文件名附加上 commit SHA
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
