name: Build Marshalsec

on:
  workflow_dispatch:
    inputs:
      jdk_version:
        description: 'JDK 8 version'
        required: true
        default: '8.0.392+8'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'mbechler/marshalsec'
        
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.392+8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven (Skip Tests)
      run: mvn -B clean package -DskipTests
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: marshalsec-jar
        path: target/marshalsec-*-all.jar
        
    - name: List generated files
      run: ls -la target/
